# Site settings
title: "unreal4u's blog"
email: me@unreal4u.com
description: Because my reality... is just your virtuality
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.unreal4u.com" # the base hostname & protocol for your site
twitter_username: unreal4u
github_username:  unreal4u
analytics :
  tracking_id : 'UA-7167806-2'
markdown: kramdown
excerpt_separator: "<!-- more -->"
permalink: /:year/:month/:title/
paginate: 10
paginate_path: "/page/:num/"
gems:
  - jekyll-sitemap
bootstrap:
  version : "3.3.4"
jquery:
  version : "2.1.3"

# SASS settings
sass:
  style: :compressed
  sass_dir: css
